import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Links from "./components/links";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="w-screen h-screen overflow-hidden">
          <div className="w-full min-h-full p-10 space-y-12 overflow-x-hidden overflow-y-auto">
            <div className="flex-1 flex items-center justify-between">
              <h1 className="text-2xl font-bold">My Next JS Application!</h1>
              <Links />
            </div>
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
